### ISSUE TITLE
 wait() got an unexpected keyword argument 'loop'

### ISSUE THREAD

**Issue by sgottscho** [J3n50m4t/Home-Assistant-DreamScreen-Service#47]
Just started receiving the following error when trying to run the dreamscreen service.

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/dreamscreen/__init__.py:176 
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22)) 
First occurred: 9:06:33 AM (7 occurrences) 
Last logged: 9:08:12 AM

[139867467491664] wait() got an unexpected keyword argument 'loop'
[139868267272256] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/dreamscreen/__init__.py", line 176, in async_handle_dreamscreen_services
    await asyncio.wait(updates, loop=hass.loop)
TypeError: wait() got an unexpected keyword argument 'loop'

**Comment by zanix** [comment]
I got this error as well, I replaced line 176 in `init.py` with this

```python
await asyncio.wait(updates)
```

The service seems to still work. However, I am no python expert so I'm not entirely sure this is the correct way to fix this.

**Comment by sgottscho** [comment]
Thank did the trick.

Thank You

**Comment by zanix** [comment]
This was fixed in #48
